export interface ProgramsPdfOptions {
  organizationName: string;
  organizationLogo?: string;
  loggedInName: string;
  loggedInEmail?: string;
  loggedInPhone?: string;
  columns: string[];
  rows: (string | number)[][];
  dateRangeText?: string;
  // Optional rendering options inspired by existing demo
  scale?: number; // html2canvas scale
  orientation?: "p" | "l"; // portrait | landscape
  pageSize?: "a4" | "a3"; // PDF page size
  imageFormat?: "PNG" | "JPEG" | "JPG"; // jsPDF image format
  imageQuality?: number; // 0..1 for JPEG quality
}

export async function exportProgramsToPDF(options: ProgramsPdfOptions) {
  const {
    organizationName,
    organizationLogo,
    loggedInName,
    loggedInEmail = "",
    loggedInPhone = "",
    columns,
    rows,
    dateRangeText,
    scale = 1.3,
    orientation = "p",
    pageSize = "a4",
    imageFormat = "JPEG",
    imageQuality = 0.9,
  } = options;

  const container = document.createElement("div");
  container.style.padding = "16px";
  container.style.background = "#fff";
  container.style.color = "#000";
  container.style.fontSize = "12px";
  container.style.lineHeight = "1.4";
  container.style.width = "1190px";

  const header = document.createElement("div");
  header.style.display = "flex";
  header.style.alignItems = "center";
  header.style.gap = "12px";
  header.style.marginBottom = "12px";
  if (organizationLogo) {
    const img = document.createElement("img");
    img.src = organizationLogo;
    img.crossOrigin = "anonymous";
    img.style.height = "40px";
    img.style.width = "40px";
    img.style.objectFit = "contain";
    img.style.borderRadius = "6px";
    img.style.border = "1px solid #eee";
    header.appendChild(img);
  }
  const orgNameEl = document.createElement("div");
  orgNameEl.style.fontWeight = "600";
  orgNameEl.style.fontSize = "16px";
  orgNameEl.style.paddingBottom = "20px";
  orgNameEl.textContent = organizationName;
  header.appendChild(orgNameEl);
  if (dateRangeText) {
    const dateRangeEl = document.createElement("div");
    dateRangeEl.style.marginLeft = "auto";
    dateRangeEl.style.fontSize = "12px";
    dateRangeEl.textContent = dateRangeText;
    header.appendChild(dateRangeEl);
  }
  container.appendChild(header);

  const tableEl = document.createElement("table");
  tableEl.style.borderCollapse = "collapse";
  tableEl.style.width = "100%";
  const thead = document.createElement("thead");
  const headRow = document.createElement("tr");
  columns.forEach((c) => {
    const th = document.createElement("th");
    th.textContent = c;
    th.style.textAlign = "left";
    th.style.border = "1px solid #ddd";
    th.style.padding = "6px";
    headRow.appendChild(th);
  });
  thead.appendChild(headRow);
  tableEl.appendChild(thead);
  const tbody = document.createElement("tbody");
  rows.forEach((row) => {
    const tr = document.createElement("tr");
    row.forEach((cell) => {
      const td = document.createElement("td");
      td.textContent = String(cell ?? "");
      td.style.border = "1px solid #ddd";
      td.style.padding = "6px";
      tr.appendChild(td);
    });
    tbody.appendChild(tr);
  });
  tableEl.appendChild(tbody);
  container.appendChild(tableEl);

  const footer = document.createElement("div");
  footer.style.marginTop = "12px";
  footer.style.borderTop = "1px solid #eee";
  footer.style.paddingTop = "8px";
  footer.style.fontSize = "12px";
  footer.textContent = `Generated by: ${loggedInName} | ${loggedInEmail} | ${loggedInPhone}`;
  container.appendChild(footer);

  document.body.appendChild(container);

  const { default: html2canvas } = await import("html2canvas");
  const { jsPDF } = await import("jspdf");
  const canvas = await html2canvas(container as any, {
    scale,
    useCORS: true,
    allowTaint: true,
    backgroundColor: "#ffffff",
    width: (container as any).scrollWidth || 1190,
    height: (container as any).scrollHeight,
  });
  // Downscale to further reduce filesize
  const maxExportWidthPx = 992; // smaller than 1190 to reduce pixels
  const ratio = Math.min(1, maxExportWidthPx / canvas.width);
  const outCanvas = document.createElement("canvas");
  outCanvas.width = Math.floor(canvas.width * ratio);
  outCanvas.height = Math.floor(canvas.height * ratio);
  const outCtx = outCanvas.getContext("2d");
  outCtx!.imageSmoothingQuality = "high";
  outCtx!.drawImage(canvas, 0, 0, outCanvas.width, outCanvas.height);

  let imgData = outCanvas.toDataURL(`image/${imageFormat.toLowerCase()}`, imageQuality);
  let addFormat: "PNG" | "JPEG" = /data:image\/(jpeg|jpg)/i.test(imgData) ? "JPEG" : "PNG";
  const pdfMm = new jsPDF(orientation, "mm", pageSize);
  const pageWidth = pdfMm.internal.pageSize.getWidth();
  const pageHeight = pdfMm.internal.pageSize.getHeight();
  // Slice approach: add only the visible page slice per PDF page
  const scalePdf = pageWidth / outCanvas.width;
  const sliceHeightCanvasPx = Math.floor(pageHeight / scalePdf);
  const sliceCanvas = document.createElement("canvas");
  sliceCanvas.width = outCanvas.width;
  sliceCanvas.height = sliceHeightCanvasPx;
  const sliceCtx = sliceCanvas.getContext("2d");

  // 20px top/bottom padding per page (in canvas px) converted to mm
  const marginPx = 20;
  const marginMm = marginPx * scalePdf;

  for (let y = 0, pageIndex = 0; y < outCanvas.height; y += sliceHeightCanvasPx, pageIndex++) {
    if (pageIndex > 0) pdfMm.addPage();
    const currentSliceHeight = Math.min(sliceHeightCanvasPx, outCanvas.height - y);
    if (sliceCanvas.height !== currentSliceHeight) sliceCanvas.height = currentSliceHeight;
    sliceCtx!.clearRect(0, 0, sliceCanvas.width, sliceCanvas.height);
    sliceCtx!.drawImage(
      outCanvas,
      0,
      y,
      outCanvas.width,
      currentSliceHeight,
      0,
      0,
      sliceCanvas.width,
      currentSliceHeight
    );
    let sliceDataUrl = sliceCanvas.toDataURL(`image/${imageFormat.toLowerCase()}`, imageQuality);
    let sliceFormat: "PNG" | "JPEG" = /data:image\/(jpeg|jpg)/i.test(sliceDataUrl) ? "JPEG" : "PNG";
    const sliceHeightPdf = currentSliceHeight * scalePdf;
    const destY = marginMm;
    const destHeight = Math.max(0.1, sliceHeightPdf - 2 * marginMm);
    try {
      pdfMm.addImage(sliceDataUrl, sliceFormat, 0, destY, pageWidth, destHeight);
    } catch (e) {
      sliceDataUrl = sliceCanvas.toDataURL("image/jpeg", Math.min(Math.max(imageQuality, 0.4), 0.9));
      sliceFormat = "JPEG";
      pdfMm.addImage(sliceDataUrl, sliceFormat, 0, destY, pageWidth, destHeight);
    }
  }

  pdfMm.save(`programs_${Date.now()}.pdf`);
  document.body.removeChild(container);
}


